name: Voxelizer
version: 1.0
main: dev.twentyfive.voxelizer.Voxelizer
api-version: 1.18
commands:
  voxelize:
    description: Voxelize a 3d model from a .obj file
    usage: voxelize <scale> <.obj file>